[package]
name = "amnesia"
edition = "2021"
license = "MIT"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/m1guelpf/amnesia"
authors = ["Miguel Piedrafita <rust@miguel.build>"]
description = "An expressive interface for interacting with a Cache."

[dependencies]
serde = "1.0.193"
thiserror = "1.0.50"
bitcode = { version = "0.5.0", optional = true, default-features = false, features = ["serde"] }

[dev-dependencies]
tokio = { version = "1.35.0", features = ["macros", "rt-multi-thread"] }

[features]
default = ["memory"]
memory = ["dep:bitcode"]
